root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /docs/bootstrap-bundle
        permanent: false

docs:
    pattern: /docs
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /docs/bootstrap-bundle
        permanent: false

bootstrap:
    resource: "@BootstrapBundle/Resources/config/routing.yml"
    prefix:   /docs/bootstrap-bundle
